Slate UI migration
SAP-docs/preview.developer.concur.com pull request #11
Opened 2021-07-02 09:42 UTC by danra2

Slate UI Migration using 3 layers of commits. 1.) Accepting updated file changes in SlateUI. 2.) Discarding all modified markdown files. 3.) Deleting all the unnecessary swagger files following the slate ui migration for API-Explorer. 

*Please see notes for commits and comments to gain additional information.

2021-07-02 09:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP-docs/preview.developer.concur.com?pullRequest=11) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP-docs/preview.developer.concur.com?pullRequest=11) before we can accept your contribution.<br/><hr/>**d.ra** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP-docs/preview.developer.concur.com?pullRequest=11) it.</sub>

2021-07-06 10:54 UTC, bjs-code requested changes
Looking much better, just concerned about these files..


src/_data/sidebars/api-explorer.yml
src/_data/sidebars/api-reference.yml
src/_data/sidebars/tools-support.yml
src/_includes/head.html
src/_includes/header.html
src/_includes/left-navigation.html
src/_includes/scripts.html
src/_plugins/jekyll-breadcrumbs/breadcrumbs.rb
src/_plugins/jekyll-breadcrumbs/drops/breadcrumb_item.rb
src/_sass/components/back-to-top.scss
src/_sass/components/navbar-notice.scss
src/_sass/components/navbar.scss
src/_sass/main.scss
src/_sass/pages/_shared.scss
src/akamai-sureroute-test-object.html
src/api-explorer/convert-swagger.sh

I believe there are changes in these files that *undo* recent changes in the base repository.

E.g. this change will be undone....

https://github.com/concur/developer.concur.com/commit/8d6a9778e58ebbf4aa089e1bd77d22911c3c0d22#diff-8df2c8d1f0e7c1020f4e34211faa4ded835cf57c9eedc5794898055fe3574459

2021-07-06 23:10 UTC, danra2 commented
Kept header.html and head.html because both contained small styling adjustments that otherwise when removed adjusted the view. Header.html also contained various slate-ui changes in the pathname, those were the only immediate changes I noticed. 

Jekyll breadcrumbs, looks like there were no actual changes from the original, but I replaced them with the original just in case. Same goes for the drops/breadcrumbe_item.rb. The remaining files have all been reset to their previous state.

2021-07-07 09:56 UTC, bjs-code approved these changes

2021-07-07 09:56 UTC, merged