making changes
SAP-docs/preview.developer.concur.com pull request #528
Opened 2023-03-02 08:28 UTC by njkmr0027

2023-03-02 20:27 UTC, RoAnnC1 commented on src/api-reference/financial-integration/v4.financial-integration-service-use-cases.markdown
> +
@njkmr0027 You have this styled as a heading, but it's really just a paragraph. Does it need to be bold? Could we style it as a note? Let me know and I can fix the formatting.

2023-03-02 20:28 UTC, RoAnnC1 commented on src/api-reference/financial-integration/v4.financial-integration-service-use-cases.markdown
> +   When the Request is created and FGI is enabled for a Group that an employee belongs to, during the workflow, when the Funds Reservation step is reached, the workflow is paused, an event ___ is pub
What is the long ___ for here?

2023-03-02 20:29 UTC, RoAnnC1 commented on src/api-reference/financial-integration/v4.financial-integration-service-use-cases.markdown
> +•	A Request Release Payload is made available to the financial system and the event ___ is published
Same comment as for line 677.

2023-03-02 20:30 UTC, RoAnnC1 requested changes
@njkmr0027 Have a couple of questions. Once you answer or resolve I'll merge this and do a little editing.

2023-03-03 13:58 UTC, njkmr0027 commented on src/api-reference/financial-integration/v4.financial-integration-service-use-cases.markdown
> +•	A Request Release Payload is made available to the financial system and the event ___ is published
updated the document

2023-03-03 17:52 UTC, RoAnnC1 approved these changes

2023-03-03 17:52 UTC, merged