FINS-6978: Add payroll json format under financial integration
SAP-docs/preview.developer.concur.com pull request #654
Opened 2023-05-19 18:02 UTC by sibidominic

2023-05-22 17:32 UTC, srikanthbabu133 approved these changes
+1

2023-06-14 04:44 UTC, MarcBell-SAP requested changes
Please fix the issues I left in the comments. I'll merge this after that's done.

2023-06-14 04:44 UTC, MarcBell-SAP commented on src/api-reference/financial-integration/v4.financial-documents-schema.markdown
> +`expenseEntry`|`Array`| Array of [Payroll - ExpenseEntry](#scprlexpent)               |***
This should link to the "Payroll - Employee" schema but instead links to the "Expense - Employee" schema. Please fix this.

2023-06-14 04:44 UTC, MarcBell-SAP commented on src/api-reference/financial-integration/v4.financial-documents-schema.markdown
> +`itineraryHeader`|`Object`|[Payroll - ItineraryHeader](#scprlItnryHdr)|Header with general information about the itinerary
This is a dead link. Clicking on it does not go anywhere. Please fix.

2023-06-14 04:44 UTC, MarcBell-SAP commented on src/api-reference/financial-integration/v4.financial-documents-schema.markdown
> +`dailyAllowanceDetails`|`Array`| Array of [Payroll - DailyAllowanceDetail](#scprldlyallwnceDtl)|List of summarized and detailed daily travel allowance calculation results of the itinerary.
This is a dead link. Clicking on it does not go anywhere. Please fix.

2023-06-14 04:44 UTC, MarcBell-SAP commented on src/api-reference/financial-integration/v4.financial-documents-schema.markdown
> +`itineraryResultHeader`|`Object`| [Payroll - ItineraryResultHeader]($scprlitnryRsltHdr)|General data of the itinerary
This link creates a 404 error. See below:
"404 - page not found
The 
6322377c98f77a5a7f86fd2ee548617c63bdac8c

 branch of 
preview.developer.concur.com

 does not contain the path 
src/api-reference/financial-integration/$scprlitnryRsltHdr."

2023-06-16 04:55 UTC, MarcBell-SAP commented on src/api-reference/financial-integration/v4.financial-documents-schema.markdown
> +`expenseEntry`|`Array`| Array of [Payroll - ExpenseEntry](#scprlexpent)               |***
Fixed. Tested and it works.

2023-06-16 05:08 UTC, MarcBell-SAP commented on src/api-reference/financial-integration/v4.financial-documents-schema.markdown
> +`itineraryResultHeader`|`Object`| [Payroll - ItineraryResultHeader]($scprlitnryRsltHdr)|General data of the itinerary
This no longer creates a 404 error. However, it is now a dead link. Please fix.

2023-06-16 05:08 UTC, MarcBell-SAP commented on src/api-reference/financial-integration/v4.financial-documents-schema.markdown
> +`dailyAllowanceDetails`|`Array`| Array of [Payroll - DailyAllowanceDetail](#scprldlyallwnceDtl)|List of summarized and detailed daily travel allowance calculation results of the itinerary.
This is still a dead link. Please fix.

2023-06-16 05:08 UTC, MarcBell-SAP commented on src/api-reference/financial-integration/v4.financial-documents-schema.markdown
> +`itineraryHeader`|`Object`|[Payroll - ItineraryHeader](#scprlItnryHdr)|Header with general information about the itinerary
This is still a dead link. Please fix.

2023-07-28 21:46 UTC, MarcBell-SAP commented on src/api-reference/financial-integration/v4.financial-documents-schema.markdown
> +`itineraryHeader`|`Object`|[Payroll - ItineraryHeader](#scprlItnryHdr)|Header with general information about the itinerary
Fixed. Tested and works.

2023-07-28 21:47 UTC, MarcBell-SAP commented on src/api-reference/financial-integration/v4.financial-documents-schema.markdown
> +`dailyAllowanceDetails`|`Array`| Array of [Payroll - DailyAllowanceDetail](#scprldlyallwnceDtl)|List of summarized and detailed daily travel allowance calculation results of the itinerary.
Fixed. Tested and works.

2023-07-28 21:48 UTC, MarcBell-SAP commented on src/api-reference/financial-integration/v4.financial-documents-schema.markdown
> +`itineraryResultHeader`|`Object`| [Payroll - ItineraryResultHeader]($scprlitnryRsltHdr)|General data of the itinerary
Fixed. Tested and works.

2023-07-28 21:53 UTC, MarcBell-SAP approved these changes
:shipit:

2023-07-28 21:54 UTC, merged