API Success Review - Report Comments (POST, PUT and DELETE v4)
SAP-docs/preview.developer.concur.com pull request #665
Opened 2023-05-29 12:09 UTC by I573832

2023-05-30 11:29 UTC, GeethaMaiKK requested changes

2023-05-30 11:29 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +`expense.report.read` - Refer to [Scope Usage](#scope-usage) for full details.
expense.report.readwrite scope is used for POST API. Please refer https://github.concur.com/inception/expense-report-service/blob/develop/src/main/java/com/concur/expense/web/controllers/CommentController.java#L140

2023-05-30 11:29 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +* [200 OK](https://tools.ietf.org/html/rfc7231#section-6.3.2)
https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.1 refers to 200 OK. Please check other links as well.

2023-05-30 11:29 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +
Don't we require to add the request body for POST?

2023-05-30 11:29 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +`expense.report.read` - Refer to [Scope Usage](#scope-usage) for full details.
expense.report.readwrite scope is used for PATCH API. Please refer https://github.concur.com/inception/expense-report-service/blob/develop/src/main/java/com/concur/expense/web/controllers/CommentController.java#L172

2023-05-30 11:29 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +
Don't we require to add the request body for PATCH? Please refer other files which has POST and PATCH APIs.

2023-05-30 11:29 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +
We have a optional parameter `accept-language`.  Please check that we should add that too or not.

2023-05-30 11:29 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +
We have a optional parameter `accept-language`.  Please check that we should add that too or not.

2023-05-30 11:29 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +* [200 OK](https://tools.ietf.org/html/rfc7231#section-6.3.2)
https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.1 refers to 200 OK. Please check other links as well.

2023-05-30 11:29 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +`expense.report.read` - Refer to [Scope Usage](#scope-usage) for full details.
expense.report.delete scope is used for DELETE API. Please refer
https://github.concur.com/inception/expense-report-service/blob/develop/src/main/java/com/concur/expense/web/controllers/CommentController.java#L206

2023-05-30 11:29 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +
We have a optional parameter accept-language. Please check that we should add that too or not.

2023-05-30 11:29 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +* [204 No Content](https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.5)
https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.1 refers to 200 OK. Please check other links as well.

2023-05-30 11:38 UTC, GeethaMaiKK requested changes

2023-05-30 11:38 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +* [Report Header Comments Response](#report-header-comments-response-schema)
This is not the response for the POST API. This is the response for GET API. I think you have to create a new table for POST response with uri.

2023-05-30 11:38 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +* [Report Header Comments Response](#report-header-comments-response-schema)
This is not the response for the PATCH API. This is the response for GET API. I think you have to create a new table for PATCH response with uri.

2023-05-30 11:38 UTC, GeethaMaiKK commented on src/api-reference/expense/expense-report/v4.comments.markdown
> +* [Report Header Comments Response](#report-header-comments-response-schema)
We don't have any response payload for DELETE API. Please check other files which has same scenario.

2023-08-23 16:48 UTC, RoAnnC1 approved these changes
:shipit:

2023-08-23 16:48 UTC, merged